// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IMigration)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMigration is a mock of IMigration interface.
type MockIMigration struct {
	ctrl     *gomock.Controller
	recorder *MockIMigrationMockRecorder
}

// MockIMigrationMockRecorder is the mock recorder for MockIMigration.
type MockIMigrationMockRecorder struct {
	mock *MockIMigration
}

// NewMockIMigration creates a new mock instance.
func NewMockIMigration(ctrl *gomock.Controller) *MockIMigration {
	mock := &MockIMigration{ctrl: ctrl}
	mock.recorder = &MockIMigrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMigration) EXPECT() *MockIMigrationMockRecorder {
	return m.recorder
}

// RunMigrate mocks base method.
func (m *MockIMigration) RunMigrate(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunMigrate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunMigrate indicates an expected call of RunMigrate.
func (mr *MockIMigrationMockRecorder) RunMigrate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunMigrate", reflect.TypeOf((*MockIMigration)(nil).RunMigrate), arg0)
}
