// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IAuth2FARepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuth2FARepository is a mock of IAuth2FARepository interface.
type MockIAuth2FARepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuth2FARepositoryMockRecorder
}

// MockIAuth2FARepositoryMockRecorder is the mock recorder for MockIAuth2FARepository.
type MockIAuth2FARepositoryMockRecorder struct {
	mock *MockIAuth2FARepository
}

// NewMockIAuth2FARepository creates a new mock instance.
func NewMockIAuth2FARepository(ctrl *gomock.Controller) *MockIAuth2FARepository {
	mock := &MockIAuth2FARepository{ctrl: ctrl}
	mock.recorder = &MockIAuth2FARepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuth2FARepository) EXPECT() *MockIAuth2FARepositoryMockRecorder {
	return m.recorder
}

// ClearRecoveryCode mocks base method.
func (m *MockIAuth2FARepository) ClearRecoveryCode(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRecoveryCode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRecoveryCode indicates an expected call of ClearRecoveryCode.
func (mr *MockIAuth2FARepositoryMockRecorder) ClearRecoveryCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRecoveryCode", reflect.TypeOf((*MockIAuth2FARepository)(nil).ClearRecoveryCode), arg0, arg1)
}

// Create mocks base method.
func (m *MockIAuth2FARepository) Create(arg0 context.Context, arg1 entity.TwoFAEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIAuth2FARepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAuth2FARepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIAuth2FARepository) Delete(arg0 context.Context, arg1 entity.UserIDEntity, arg2 entity.TwoFAType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIAuth2FARepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIAuth2FARepository)(nil).Delete), arg0, arg1, arg2)
}

// GetByUserID mocks base method.
func (m *MockIAuth2FARepository) GetByUserID(arg0 context.Context, arg1 entity.UserIDEntity) ([]entity.TwoFAEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entity.TwoFAEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockIAuth2FARepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockIAuth2FARepository)(nil).GetByUserID), arg0, arg1)
}

// GetByUserIDAndType mocks base method.
func (m *MockIAuth2FARepository) GetByUserIDAndType(arg0 context.Context, arg1 entity.UserIDEntity, arg2 entity.TwoFAType) (entity.TwoFAEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndType", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.TwoFAEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUserIDAndType indicates an expected call of GetByUserIDAndType.
func (mr *MockIAuth2FARepositoryMockRecorder) GetByUserIDAndType(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndType", reflect.TypeOf((*MockIAuth2FARepository)(nil).GetByUserIDAndType), arg0, arg1, arg2)
}

// GetRecoveryCode mocks base method.
func (m *MockIAuth2FARepository) GetRecoveryCode(arg0 context.Context, arg1 entity.UserIDEntity) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecoveryCode", arg0, arg1)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecoveryCode indicates an expected call of GetRecoveryCode.
func (mr *MockIAuth2FARepositoryMockRecorder) GetRecoveryCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecoveryCode", reflect.TypeOf((*MockIAuth2FARepository)(nil).GetRecoveryCode), arg0, arg1)
}

// SetRecoveryCode mocks base method.
func (m *MockIAuth2FARepository) SetRecoveryCode(arg0 context.Context, arg1 entity.UserIDEntity, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecoveryCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecoveryCode indicates an expected call of SetRecoveryCode.
func (mr *MockIAuth2FARepositoryMockRecorder) SetRecoveryCode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecoveryCode", reflect.TypeOf((*MockIAuth2FARepository)(nil).SetRecoveryCode), arg0, arg1, arg2)
}
