// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IPasskeyRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIPasskeyRepository is a mock of IPasskeyRepository interface.
type MockIPasskeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPasskeyRepositoryMockRecorder
}

// MockIPasskeyRepositoryMockRecorder is the mock recorder for MockIPasskeyRepository.
type MockIPasskeyRepositoryMockRecorder struct {
	mock *MockIPasskeyRepository
}

// NewMockIPasskeyRepository creates a new mock instance.
func NewMockIPasskeyRepository(ctrl *gomock.Controller) *MockIPasskeyRepository {
	mock := &MockIPasskeyRepository{ctrl: ctrl}
	mock.recorder = &MockIPasskeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasskeyRepository) EXPECT() *MockIPasskeyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPasskeyRepository) Create(arg0 context.Context, arg1 entity.PasskeyEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIPasskeyRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPasskeyRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIPasskeyRepository) Delete(arg0 context.Context, arg1 int64, arg2 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPasskeyRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPasskeyRepository)(nil).Delete), arg0, arg1, arg2)
}

// DeleteByUserID mocks base method.
func (m *MockIPasskeyRepository) DeleteByUserID(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockIPasskeyRepositoryMockRecorder) DeleteByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockIPasskeyRepository)(nil).DeleteByUserID), arg0, arg1)
}

// GetByCredentialID mocks base method.
func (m *MockIPasskeyRepository) GetByCredentialID(arg0 context.Context, arg1 []byte) (entity.PasskeyEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCredentialID", arg0, arg1)
	ret0, _ := ret[0].(entity.PasskeyEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByCredentialID indicates an expected call of GetByCredentialID.
func (mr *MockIPasskeyRepositoryMockRecorder) GetByCredentialID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCredentialID", reflect.TypeOf((*MockIPasskeyRepository)(nil).GetByCredentialID), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockIPasskeyRepository) GetByUserID(arg0 context.Context, arg1 entity.UserIDEntity) ([]entity.PasskeyEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entity.PasskeyEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockIPasskeyRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockIPasskeyRepository)(nil).GetByUserID), arg0, arg1)
}

// UpdateLastUsedAt mocks base method.
func (m *MockIPasskeyRepository) UpdateLastUsedAt(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsedAt", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsedAt indicates an expected call of UpdateLastUsedAt.
func (mr *MockIPasskeyRepositoryMockRecorder) UpdateLastUsedAt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsedAt", reflect.TypeOf((*MockIPasskeyRepository)(nil).UpdateLastUsedAt), arg0, arg1)
}

// UpdateSignCount mocks base method.
func (m *MockIPasskeyRepository) UpdateSignCount(arg0 context.Context, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSignCount", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSignCount indicates an expected call of UpdateSignCount.
func (mr *MockIPasskeyRepositoryMockRecorder) UpdateSignCount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSignCount", reflect.TypeOf((*MockIPasskeyRepository)(nil).UpdateSignCount), arg0, arg1, arg2)
}
