// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IAuthRefreshTokenRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthRefreshTokenRepository is a mock of IAuthRefreshTokenRepository interface.
type MockIAuthRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthRefreshTokenRepositoryMockRecorder
}

// MockIAuthRefreshTokenRepositoryMockRecorder is the mock recorder for MockIAuthRefreshTokenRepository.
type MockIAuthRefreshTokenRepositoryMockRecorder struct {
	mock *MockIAuthRefreshTokenRepository
}

// NewMockIAuthRefreshTokenRepository creates a new mock instance.
func NewMockIAuthRefreshTokenRepository(ctrl *gomock.Controller) *MockIAuthRefreshTokenRepository {
	mock := &MockIAuthRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthRefreshTokenRepository) EXPECT() *MockIAuthRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteAllTokensByUserID mocks base method.
func (m *MockIAuthRefreshTokenRepository) DeleteAllTokensByUserID(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllTokensByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllTokensByUserID indicates an expected call of DeleteAllTokensByUserID.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) DeleteAllTokensByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllTokensByUserID", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).DeleteAllTokensByUserID), arg0, arg1)
}

// DeleteRefreshToken mocks base method.
func (m *MockIAuthRefreshTokenRepository) DeleteRefreshToken(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) DeleteRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).DeleteRefreshToken), arg0, arg1)
}

// DeleteRefreshTokenByHash mocks base method.
func (m *MockIAuthRefreshTokenRepository) DeleteRefreshTokenByHash(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenByHash", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenByHash indicates an expected call of DeleteRefreshTokenByHash.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) DeleteRefreshTokenByHash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenByHash", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).DeleteRefreshTokenByHash), arg0, arg1)
}

// IssueRefreshToken mocks base method.
func (m *MockIAuthRefreshTokenRepository) IssueRefreshToken(arg0 context.Context, arg1 entity.UserIDEntity) (entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueRefreshToken indicates an expected call of IssueRefreshToken.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) IssueRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueRefreshToken", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).IssueRefreshToken), arg0, arg1)
}

// ValidateRefreshToken mocks base method.
func (m *MockIAuthRefreshTokenRepository) ValidateRefreshToken(arg0 context.Context, arg1 string) (entity.RefreshToken, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(entity.RefreshToken)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) ValidateRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).ValidateRefreshToken), arg0, arg1)
}

// ValidateRefreshTokenHash mocks base method.
func (m *MockIAuthRefreshTokenRepository) ValidateRefreshTokenHash(arg0 context.Context, arg1 string) (entity.RefreshToken, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshTokenHash", arg0, arg1)
	ret0, _ := ret[0].(entity.RefreshToken)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateRefreshTokenHash indicates an expected call of ValidateRefreshTokenHash.
func (mr *MockIAuthRefreshTokenRepositoryMockRecorder) ValidateRefreshTokenHash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshTokenHash", reflect.TypeOf((*MockIAuthRefreshTokenRepository)(nil).ValidateRefreshTokenHash), arg0, arg1)
}
