// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IUserRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserRepository is a mock of IUserRepository interface.
type MockIUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepositoryMockRecorder
}

// MockIUserRepositoryMockRecorder is the mock recorder for MockIUserRepository.
type MockIUserRepositoryMockRecorder struct {
	mock *MockIUserRepository
}

// NewMockIUserRepository creates a new mock instance.
func NewMockIUserRepository(ctrl *gomock.Controller) *MockIUserRepository {
	mock := &MockIUserRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepository) EXPECT() *MockIUserRepositoryMockRecorder {
	return m.recorder
}

// AddUserSSOBinding mocks base method.
func (m *MockIUserRepository) AddUserSSOBinding(arg0 context.Context, arg1 entity.UserIDEntity, arg2, arg3 string, arg4, arg5 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserSSOBinding", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserSSOBinding indicates an expected call of AddUserSSOBinding.
func (mr *MockIUserRepositoryMockRecorder) AddUserSSOBinding(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserSSOBinding", reflect.TypeOf((*MockIUserRepository)(nil).AddUserSSOBinding), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Create mocks base method.
func (m *MockIUserRepository) Create(arg0 context.Context, arg1 string, arg2 []entity.UserRoleEntity) (entity.UserEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserRepository)(nil).Create), arg0, arg1, arg2)
}

// CreateUserBySSO mocks base method.
func (m *MockIUserRepository) CreateUserBySSO(arg0 context.Context, arg1, arg2 string, arg3, arg4 *string, arg5 []entity.UserRoleEntity) (entity.UserEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserBySSO", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserBySSO indicates an expected call of CreateUserBySSO.
func (mr *MockIUserRepositoryMockRecorder) CreateUserBySSO(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserBySSO", reflect.TypeOf((*MockIUserRepository)(nil).CreateUserBySSO), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Delete mocks base method.
func (m *MockIUserRepository) Delete(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIUserRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserRepository)(nil).Delete), arg0, arg1)
}

// DeleteUserSSOBinding mocks base method.
func (m *MockIUserRepository) DeleteUserSSOBinding(arg0 context.Context, arg1 entity.UserIDEntity, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSSOBinding", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSSOBinding indicates an expected call of DeleteUserSSOBinding.
func (mr *MockIUserRepositoryMockRecorder) DeleteUserSSOBinding(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSSOBinding", reflect.TypeOf((*MockIUserRepository)(nil).DeleteUserSSOBinding), arg0, arg1, arg2)
}

// DeleteUserWithAllData mocks base method.
func (m *MockIUserRepository) DeleteUserWithAllData(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserWithAllData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserWithAllData indicates an expected call of DeleteUserWithAllData.
func (mr *MockIUserRepositoryMockRecorder) DeleteUserWithAllData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserWithAllData", reflect.TypeOf((*MockIUserRepository)(nil).DeleteUserWithAllData), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockIUserRepository) GetByEmail(arg0 context.Context, arg1 string) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockIUserRepositoryMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockIUserRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockIUserRepository) GetByID(arg0 context.Context, arg1 entity.UserIDEntity) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIUserRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIUserRepository)(nil).GetByID), arg0, arg1)
}

// GetByUsername mocks base method.
func (m *MockIUserRepository) GetByUsername(arg0 context.Context, arg1 string) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", arg0, arg1)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockIUserRepositoryMockRecorder) GetByUsername(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockIUserRepository)(nil).GetByUsername), arg0, arg1)
}

// GetUserBySSO mocks base method.
func (m *MockIUserRepository) GetUserBySSO(arg0 context.Context, arg1, arg2 string) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBySSO", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserBySSO indicates an expected call of GetUserBySSO.
func (mr *MockIUserRepositoryMockRecorder) GetUserBySSO(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBySSO", reflect.TypeOf((*MockIUserRepository)(nil).GetUserBySSO), arg0, arg1, arg2)
}

// GetUserSSOBindings mocks base method.
func (m *MockIUserRepository) GetUserSSOBindings(arg0 context.Context, arg1 entity.UserIDEntity) ([]entity.UserSSOEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSSOBindings", arg0, arg1)
	ret0, _ := ret[0].([]entity.UserSSOEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSSOBindings indicates an expected call of GetUserSSOBindings.
func (mr *MockIUserRepositoryMockRecorder) GetUserSSOBindings(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSSOBindings", reflect.TypeOf((*MockIUserRepository)(nil).GetUserSSOBindings), arg0, arg1)
}

// Update mocks base method.
func (m *MockIUserRepository) Update(arg0 context.Context, arg1 entity.UserEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUserRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserRepository)(nil).Update), arg0, arg1)
}

// UpdatePassword mocks base method.
func (m *MockIUserRepository) UpdatePassword(arg0 context.Context, arg1 entity.UserIDEntity, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIUserRepositoryMockRecorder) UpdatePassword(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIUserRepository)(nil).UpdatePassword), arg0, arg1, arg2)
}

// ValidateCredentialsByEmail mocks base method.
func (m *MockIUserRepository) ValidateCredentialsByEmail(arg0 context.Context, arg1, arg2 string) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCredentialsByEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateCredentialsByEmail indicates an expected call of ValidateCredentialsByEmail.
func (mr *MockIUserRepositoryMockRecorder) ValidateCredentialsByEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCredentialsByEmail", reflect.TypeOf((*MockIUserRepository)(nil).ValidateCredentialsByEmail), arg0, arg1, arg2)
}

// ValidateCredentialsByUsername mocks base method.
func (m *MockIUserRepository) ValidateCredentialsByUsername(arg0 context.Context, arg1, arg2 string) (entity.UserEntity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCredentialsByUsername", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.UserEntity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateCredentialsByUsername indicates an expected call of ValidateCredentialsByUsername.
func (mr *MockIUserRepositoryMockRecorder) ValidateCredentialsByUsername(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCredentialsByUsername", reflect.TypeOf((*MockIUserRepository)(nil).ValidateCredentialsByUsername), arg0, arg1, arg2)
}
