// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IToolRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	reflect "reflect"
	time "time"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIToolRepository is a mock of IToolRepository interface.
type MockIToolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIToolRepositoryMockRecorder
}

// MockIToolRepositoryMockRecorder is the mock recorder for MockIToolRepository.
type MockIToolRepositoryMockRecorder struct {
	mock *MockIToolRepository
}

// NewMockIToolRepository creates a new mock instance.
func NewMockIToolRepository(ctrl *gomock.Controller) *MockIToolRepository {
	mock := &MockIToolRepository{ctrl: ctrl}
	mock.recorder = &MockIToolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIToolRepository) EXPECT() *MockIToolRepositoryMockRecorder {
	return m.recorder
}

// AllTools mocks base method.
func (m *MockIToolRepository) AllTools(arg0 entity.UserIDEntity) (entity.ToolsEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllTools", arg0)
	ret0, _ := ret[0].(entity.ToolsEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllTools indicates an expected call of AllTools.
func (mr *MockIToolRepositoryMockRecorder) AllTools(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllTools", reflect.TypeOf((*MockIToolRepository)(nil).AllTools), arg0)
}

// CreateTool mocks base method.
func (m *MockIToolRepository) CreateTool(arg0 entity.UserIDEntity, arg1 entity.ToolEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTool", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTool indicates an expected call of CreateTool.
func (mr *MockIToolRepositoryMockRecorder) CreateTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTool", reflect.TypeOf((*MockIToolRepository)(nil).CreateTool), arg0, arg1)
}

// DeleteTool mocks base method.
func (m *MockIToolRepository) DeleteTool(arg0 entity.UserIDEntity, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTool", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTool indicates an expected call of DeleteTool.
func (mr *MockIToolRepositoryMockRecorder) DeleteTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTool", reflect.TypeOf((*MockIToolRepository)(nil).DeleteTool), arg0, arg1)
}

// ToolsLastUpdatedAt mocks base method.
func (m *MockIToolRepository) ToolsLastUpdatedAt(arg0 entity.UserIDEntity) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToolsLastUpdatedAt", arg0)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToolsLastUpdatedAt indicates an expected call of ToolsLastUpdatedAt.
func (mr *MockIToolRepositoryMockRecorder) ToolsLastUpdatedAt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToolsLastUpdatedAt", reflect.TypeOf((*MockIToolRepository)(nil).ToolsLastUpdatedAt), arg0)
}

// UpdateTool mocks base method.
func (m *MockIToolRepository) UpdateTool(arg0 entity.UserIDEntity, arg1 entity.ToolEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTool", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTool indicates an expected call of UpdateTool.
func (mr *MockIToolRepositoryMockRecorder) UpdateTool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTool", reflect.TypeOf((*MockIToolRepository)(nil).UpdateTool), arg0, arg1)
}
