// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IRdsClient)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
)

// MockIRdsClient is a mock of IRdsClient interface.
type MockIRdsClient struct {
	ctrl     *gomock.Controller
	recorder *MockIRdsClientMockRecorder
}

// MockIRdsClientMockRecorder is the mock recorder for MockIRdsClient.
type MockIRdsClientMockRecorder struct {
	mock *MockIRdsClient
}

// NewMockIRdsClient creates a new mock instance.
func NewMockIRdsClient(ctrl *gomock.Controller) *MockIRdsClient {
	mock := &MockIRdsClient{ctrl: ctrl}
	mock.recorder = &MockIRdsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRdsClient) EXPECT() *MockIRdsClientMockRecorder {
	return m.recorder
}

// DB mocks base method.
func (m *MockIRdsClient) DB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockIRdsClientMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockIRdsClient)(nil).DB))
}
