// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IAuthAccessTokenRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	context "context"
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIAuthAccessTokenRepository is a mock of IAuthAccessTokenRepository interface.
type MockIAuthAccessTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthAccessTokenRepositoryMockRecorder
}

// MockIAuthAccessTokenRepositoryMockRecorder is the mock recorder for MockIAuthAccessTokenRepository.
type MockIAuthAccessTokenRepositoryMockRecorder struct {
	mock *MockIAuthAccessTokenRepository
}

// NewMockIAuthAccessTokenRepository creates a new mock instance.
func NewMockIAuthAccessTokenRepository(ctrl *gomock.Controller) *MockIAuthAccessTokenRepository {
	mock := &MockIAuthAccessTokenRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthAccessTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthAccessTokenRepository) EXPECT() *MockIAuthAccessTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteAccessToken mocks base method.
func (m *MockIAuthAccessTokenRepository) DeleteAccessToken(arg0 context.Context, arg1 entity.AccessToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessToken indicates an expected call of DeleteAccessToken.
func (mr *MockIAuthAccessTokenRepositoryMockRecorder) DeleteAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessToken", reflect.TypeOf((*MockIAuthAccessTokenRepository)(nil).DeleteAccessToken), arg0, arg1)
}

// DeleteAllTokensByUserID mocks base method.
func (m *MockIAuthAccessTokenRepository) DeleteAllTokensByUserID(arg0 context.Context, arg1 entity.UserIDEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllTokensByUserID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllTokensByUserID indicates an expected call of DeleteAllTokensByUserID.
func (mr *MockIAuthAccessTokenRepositoryMockRecorder) DeleteAllTokensByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllTokensByUserID", reflect.TypeOf((*MockIAuthAccessTokenRepository)(nil).DeleteAllTokensByUserID), arg0, arg1)
}

// IssueAccessToken mocks base method.
func (m *MockIAuthAccessTokenRepository) IssueAccessToken(arg0 context.Context, arg1 entity.UserIDEntity, arg2 string) (entity.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockIAuthAccessTokenRepositoryMockRecorder) IssueAccessToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockIAuthAccessTokenRepository)(nil).IssueAccessToken), arg0, arg1, arg2)
}

// ValidateAccessToken mocks base method.
func (m *MockIAuthAccessTokenRepository) ValidateAccessToken(arg0 context.Context, arg1 string) (entity.AccessToken, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", arg0, arg1)
	ret0, _ := ret[0].(entity.AccessToken)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MockIAuthAccessTokenRepositoryMockRecorder) ValidateAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MockIAuthAccessTokenRepository)(nil).ValidateAccessToken), arg0, arg1)
}
