// Code generated by MockGen. DO NOT EDIT.
// Source: ya-tool-craft/internal/domain/repository (interfaces: IGlobalScriptRepository)

// Package mock_gen is a generated GoMock package.
package mock_gen

import (
	reflect "reflect"
	entity "ya-tool-craft/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIGlobalScriptRepository is a mock of IGlobalScriptRepository interface.
type MockIGlobalScriptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIGlobalScriptRepositoryMockRecorder
}

// MockIGlobalScriptRepositoryMockRecorder is the mock recorder for MockIGlobalScriptRepository.
type MockIGlobalScriptRepositoryMockRecorder struct {
	mock *MockIGlobalScriptRepository
}

// NewMockIGlobalScriptRepository creates a new mock instance.
func NewMockIGlobalScriptRepository(ctrl *gomock.Controller) *MockIGlobalScriptRepository {
	mock := &MockIGlobalScriptRepository{ctrl: ctrl}
	mock.recorder = &MockIGlobalScriptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGlobalScriptRepository) EXPECT() *MockIGlobalScriptRepositoryMockRecorder {
	return m.recorder
}

// GetGlobalScript mocks base method.
func (m *MockIGlobalScriptRepository) GetGlobalScript(arg0 entity.UserIDEntity) (*entity.GlobalScriptEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalScript", arg0)
	ret0, _ := ret[0].(*entity.GlobalScriptEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalScript indicates an expected call of GetGlobalScript.
func (mr *MockIGlobalScriptRepositoryMockRecorder) GetGlobalScript(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalScript", reflect.TypeOf((*MockIGlobalScriptRepository)(nil).GetGlobalScript), arg0)
}

// UpdateGlobalScript mocks base method.
func (m *MockIGlobalScriptRepository) UpdateGlobalScript(arg0 entity.UserIDEntity, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGlobalScript", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGlobalScript indicates an expected call of UpdateGlobalScript.
func (mr *MockIGlobalScriptRepositoryMockRecorder) UpdateGlobalScript(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGlobalScript", reflect.TypeOf((*MockIGlobalScriptRepository)(nil).UpdateGlobalScript), arg0, arg1)
}
