// Code generated by go generate; DO NOT EDIT.
package error_code

type ErrorCodeConst string

const (
	ErrorCodeCannotDeleteLastSSOBinding      ErrorCodeConst = "CannotDeleteLastSSOBinding"
	ErrorCodeDirectoryNotFound               ErrorCodeConst = "DirectoryNotFound"
	ErrorCodeFileAlreadyExists               ErrorCodeConst = "FileAlreadyExists"
	ErrorCodeFileNotFound                    ErrorCodeConst = "FileNotFound"
	ErrorCodeFileOperationFailed             ErrorCodeConst = "FileOperationFailed"
	ErrorCodeFileTooLarge                    ErrorCodeConst = "FileTooLarge"
	ErrorCodeForbidden                       ErrorCodeConst = "Forbidden"
	ErrorCodeInternalServerError             ErrorCodeConst = "InternalServerError"
	ErrorCodeInvalidAccessToken              ErrorCodeConst = "InvalidAccessToken"
	ErrorCodeInvalidCredentials              ErrorCodeConst = "InvalidCredentials"
	ErrorCodeInvalidFilePath                 ErrorCodeConst = "InvalidFilePath"
	ErrorCodeInvalidFileType                 ErrorCodeConst = "InvalidFileType"
	ErrorCodeInvalidParameter                ErrorCodeConst = "InvalidParameter"
	ErrorCodeInvalidParameters               ErrorCodeConst = "InvalidParameters"
	ErrorCodeInvalidRecoveryCode             ErrorCodeConst = "InvalidRecoveryCode"
	ErrorCodeInvalidRefreshToken             ErrorCodeConst = "InvalidRefreshToken"
	ErrorCodeInvalidTotpCode                 ErrorCodeConst = "InvalidTotpCode"
	ErrorCodeOauthTokenUnavailable           ErrorCodeConst = "OauthTokenUnavailable"
	ErrorCodePasswordLoginIsNotEnabled       ErrorCodeConst = "PasswordLoginIsNotEnabled"
	ErrorCodeSSOProviderAccountAlreadyBinded ErrorCodeConst = "SSOProviderAccountAlreadyBinded"
	ErrorCodeStorageQuotaExceeded            ErrorCodeConst = "StorageQuotaExceeded"
	ErrorCodeTokenNotFound                   ErrorCodeConst = "TokenNotFound"
	ErrorCodeTwoFaAlreadyEnabled             ErrorCodeConst = "TwoFaAlreadyEnabled"
	ErrorCodeTwoFaTotpIsRequiredForLogin     ErrorCodeConst = "TwoFaTotpIsRequiredForLogin"
	ErrorCodeUnauthorized                    ErrorCodeConst = "Unauthorized"
	ErrorCodeUserAlreadyExists               ErrorCodeConst = "UserAlreadyExists"
	ErrorCodeUserNotFound                    ErrorCodeConst = "UserNotFound"
)
