// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiV1GlobalScriptResponse, GetApiV1ToolsResponse, PostApiV1AuthAccessTokenResponse, PostApiV1AuthLoginResponse, PostApiV1AuthPasskeyLoginVerifyResponse, PostApiV1AuthSsoByProviderResponse } from './types.gen';

const authIssueAccessTokenResponseDtoSchemaResponseTransformer = (data: any) => {
    data.expires_in = new Date(data.expires_in);
    return data;
};

const swaggerBaseSuccessResponseAuthIssueAccessTokenResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = authIssueAccessTokenResponseDtoSchemaResponseTransformer(data.data);
    return data;
};

export const postApiV1AuthAccessTokenResponseTransformer = async (data: any): Promise<PostApiV1AuthAccessTokenResponse> => {
    data = swaggerBaseSuccessResponseAuthIssueAccessTokenResponseDtoSchemaResponseTransformer(data);
    return data;
};

const authLoginResponseDtoSchemaResponseTransformer = (data: any) => {
    data.expires_in = new Date(data.expires_in);
    data.refresh_token_expires_in = new Date(data.refresh_token_expires_in);
    return data;
};

const swaggerBaseSuccessResponseAuthLoginResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = authLoginResponseDtoSchemaResponseTransformer(data.data);
    return data;
};

export const postApiV1AuthLoginResponseTransformer = async (data: any): Promise<PostApiV1AuthLoginResponse> => {
    data = swaggerBaseSuccessResponseAuthLoginResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const postApiV1AuthPasskeyLoginVerifyResponseTransformer = async (data: any): Promise<PostApiV1AuthPasskeyLoginVerifyResponse> => {
    data = swaggerBaseSuccessResponseAuthLoginResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const postApiV1AuthSsoByProviderResponseTransformer = async (data: any): Promise<PostApiV1AuthSsoByProviderResponse> => {
    data = swaggerBaseSuccessResponseAuthLoginResponseDtoSchemaResponseTransformer(data);
    return data;
};

const globalScriptGetGlobalScriptResponseDtoSchemaResponseTransformer = (data: any) => {
    data.updated_at = new Date(data.updated_at);
    return data;
};

const swaggerBaseSuccessResponseGlobalScriptGetGlobalScriptResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = globalScriptGetGlobalScriptResponseDtoSchemaResponseTransformer(data.data);
    return data;
};

export const getApiV1GlobalScriptResponseTransformer = async (data: any): Promise<GetApiV1GlobalScriptResponse> => {
    data = swaggerBaseSuccessResponseGlobalScriptGetGlobalScriptResponseDtoSchemaResponseTransformer(data);
    return data;
};

const toolsAllToolsResponseDtoSchemaResponseTransformer = (data: any) => {
    data.tools_last_update_at = new Date(data.tools_last_update_at);
    return data;
};

const swaggerBaseSuccessResponseToolsAllToolsResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = toolsAllToolsResponseDtoSchemaResponseTransformer(data.data);
    return data;
};

export const getApiV1ToolsResponseTransformer = async (data: any): Promise<GetApiV1ToolsResponse> => {
    data = swaggerBaseSuccessResponseToolsAllToolsResponseDtoSchemaResponseTransformer(data);
    return data;
};
