// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'localhost:8080/' | (string & {});
};

export type AuthAuthenticatorSelectionCriteriaDto = {
    authenticatorAttachment?: string;
    requireResidentKey?: boolean;
    residentKey?: string;
    userVerification?: string;
};

export type AuthIssueAccessTokenRequestDto = {
    refresh_token: string;
};

export type AuthIssueAccessTokenResponseDto = {
    access_token: string;
    expires_in: Date;
};

export type AuthLoginRequestDto = {
    /**
     * password length should be between 6 and 32 characters
     */
    password: string;
    /**
     * username length should be between 3 and 32 characters
     */
    username: string;
};

export type AuthLoginResponseDto = {
    access_token: string;
    expires_in: Date;
    refresh_token: string;
    refresh_token_expires_in: Date;
};

export type AuthPasskeyAssertionResponseDto = {
    authenticatorData: string;
    clientDataJSON: string;
    signature: string;
    userHandle?: string;
};

export type AuthPasskeyAttestationResponseDto = {
    attestationObject: string;
    clientDataJSON: string;
    transports?: Array<string>;
};

export type AuthPasskeyChallengeResponseDto = {
    publicKey: AuthPublicKeyCredentialCreationOptionsDto;
};

export type AuthPasskeyDto = {
    backup_eligible: boolean;
    backup_state: boolean;
    created_at: string;
    credential_id: string;
    device_name: string;
    id: number;
    last_used_at: string;
};

export type AuthPasskeyGetResponseDto = {
    passkeys: Array<AuthPasskeyDto>;
};

export type AuthPasskeyLoginChallengeResponseDto = {
    publicKey: AuthPublicKeyCredentialRequestOptionsDto;
};

export type AuthPasskeyLoginRequestDto = {
    authenticatorAttachment?: string;
    clientExtensionResults?: {
        [key: string]: unknown;
    };
    id: string;
    rawId: string;
    response: AuthPasskeyAssertionResponseDto;
    type: string;
};

export type AuthPasskeyRegisterRequestDto = {
    authenticatorAttachment?: string;
    clientExtensionResults?: {
        [key: string]: unknown;
    };
    deviceName?: string;
    id: string;
    rawId: string;
    response: AuthPasskeyAttestationResponseDto;
    type: string;
};

export type AuthPubKeyCredParamDto = {
    alg: number;
    type: string;
};

export type AuthPublicKeyCredentialCreationOptionsDto = {
    attestation: string;
    authenticatorSelection?: AuthAuthenticatorSelectionCriteriaDto;
    challenge: string;
    excludeCredentials?: Array<AuthPublicKeyCredentialDescriptorDto>;
    pubKeyCredParams: Array<AuthPubKeyCredParamDto>;
    rp: AuthRelyingPartyDto;
    timeout: number;
    user: AuthUserEntityDto;
};

export type AuthPublicKeyCredentialDescriptorDto = {
    id: string;
    transports?: Array<string>;
    type: string;
};

export type AuthPublicKeyCredentialRequestOptionsDto = {
    allowCredentials?: Array<AuthPublicKeyCredentialDescriptorDto>;
    challenge: string;
    rpId: string;
    timeout: number;
    userVerification?: string;
};

export type AuthRelyingPartyDto = {
    id: string;
    name: string;
};

export type AuthSsoBindingDeleteRequestDto = {
    provider: string;
};

export type AuthSsoBindingDto = {
    created_at: string;
    provider: string;
    provider_email: string;
    provider_user_id: string;
    provider_username: string;
};

export type AuthSsoBindingGetResponseDto = {
    bindings: Array<AuthSsoBindingDto>;
};

export type AuthSsoLoginRequestDto = {
    /**
     * username length should be between 3 and 32 characters
     */
    oauth_code: string;
};

export type AuthTwoFaDeleteRequestDto = {
    code: string;
    type: string;
};

export type AuthTwoFaGetResponseDto = {
    two_fa_list: Array<AuthTwoFaInfoDto>;
};

export type AuthTwoFaInfoDto = {
    created_at: string;
    enabled: boolean;
    type: string;
};

export type AuthTwoFaLoginRequestDto = {
    /**
     * 6-digit TOTP code from authenticator app
     */
    code: string;
    /**
     * token from login API when 2FA is required
     */
    token: string;
};

export type AuthTwoFaLoginResponseDto = {
    access_token: string;
    refresh_token: string;
};

export type AuthTwoFaRecoveryRequestDto = {
    recovery_code: string;
    token: string;
};

export type AuthTwoFaRetrieveTotpResponseDto = {
    /**
     * base64 encoded PNG image
     */
    qr_code: string;
    secret: string;
    /**
     * token for verification
     */
    token: string;
    url: string;
};

export type AuthTwoFatotpAddRequestDto = {
    /**
     * 6-digit TOTP code from authenticator app
     */
    code: string;
    /**
     * token from retrieve TOTP API
     */
    token: string;
};

export type AuthTwoFatotpAddResponseDto = {
    recovery_code: string;
};

export type AuthUserEntityDto = {
    displayName: string;
    id: string;
    name: string;
};

export const ErrorCodeErrorCodeConst = {
    /**
     * ErrorCodeCannotDeleteLastSSOBinding
     */
    ERROR_CODE_CANNOT_DELETE_LAST_SSO_BINDING: 'CannotDeleteLastSSOBinding',
    /**
     * ErrorCodeDirectoryNotFound
     */
    ERROR_CODE_DIRECTORY_NOT_FOUND: 'DirectoryNotFound',
    /**
     * ErrorCodeFileAlreadyExists
     */
    ERROR_CODE_FILE_ALREADY_EXISTS: 'FileAlreadyExists',
    /**
     * ErrorCodeFileNotFound
     */
    ERROR_CODE_FILE_NOT_FOUND: 'FileNotFound',
    /**
     * ErrorCodeFileOperationFailed
     */
    ERROR_CODE_FILE_OPERATION_FAILED: 'FileOperationFailed',
    /**
     * ErrorCodeFileTooLarge
     */
    ERROR_CODE_FILE_TOO_LARGE: 'FileTooLarge',
    /**
     * ErrorCodeForbidden
     */
    ERROR_CODE_FORBIDDEN: 'Forbidden',
    /**
     * ErrorCodeInternalServerError
     */
    ERROR_CODE_INTERNAL_SERVER_ERROR: 'InternalServerError',
    /**
     * ErrorCodeInvalidAccessToken
     */
    ERROR_CODE_INVALID_ACCESS_TOKEN: 'InvalidAccessToken',
    /**
     * ErrorCodeInvalidCredentials
     */
    ERROR_CODE_INVALID_CREDENTIALS: 'InvalidCredentials',
    /**
     * ErrorCodeInvalidFilePath
     */
    ERROR_CODE_INVALID_FILE_PATH: 'InvalidFilePath',
    /**
     * ErrorCodeInvalidFileType
     */
    ERROR_CODE_INVALID_FILE_TYPE: 'InvalidFileType',
    /**
     * ErrorCodeInvalidParameter
     */
    ERROR_CODE_INVALID_PARAMETER: 'InvalidParameter',
    /**
     * ErrorCodeInvalidParameters
     */
    ERROR_CODE_INVALID_PARAMETERS: 'InvalidParameters',
    /**
     * ErrorCodeInvalidRecoveryCode
     */
    ERROR_CODE_INVALID_RECOVERY_CODE: 'InvalidRecoveryCode',
    /**
     * ErrorCodeInvalidRefreshToken
     */
    ERROR_CODE_INVALID_REFRESH_TOKEN: 'InvalidRefreshToken',
    /**
     * ErrorCodeInvalidTotpCode
     */
    ERROR_CODE_INVALID_TOTP_CODE: 'InvalidTotpCode',
    /**
     * ErrorCodeOauthTokenUnavailable
     */
    ERROR_CODE_OAUTH_TOKEN_UNAVAILABLE: 'OauthTokenUnavailable',
    /**
     * ErrorCodePasswordLoginIsNotEnabled
     */
    ERROR_CODE_PASSWORD_LOGIN_IS_NOT_ENABLED: 'PasswordLoginIsNotEnabled',
    /**
     * ErrorCodeSSOProviderAccountAlreadyBinded
     */
    ERROR_CODE_SSO_PROVIDER_ACCOUNT_ALREADY_BINDED: 'SSOProviderAccountAlreadyBinded',
    /**
     * ErrorCodeStorageQuotaExceeded
     */
    ERROR_CODE_STORAGE_QUOTA_EXCEEDED: 'StorageQuotaExceeded',
    /**
     * ErrorCodeTokenNotFound
     */
    ERROR_CODE_TOKEN_NOT_FOUND: 'TokenNotFound',
    /**
     * ErrorCodeTwoFaAlreadyEnabled
     */
    ERROR_CODE_TWO_FA_ALREADY_ENABLED: 'TwoFaAlreadyEnabled',
    /**
     * ErrorCodeTwoFaTotpIsRequiredForLogin
     */
    ERROR_CODE_TWO_FA_TOTP_IS_REQUIRED_FOR_LOGIN: 'TwoFaTotpIsRequiredForLogin',
    /**
     * ErrorCodeUnauthorized
     */
    ERROR_CODE_UNAUTHORIZED: 'Unauthorized',
    /**
     * ErrorCodeUserAlreadyExists
     */
    ERROR_CODE_USER_ALREADY_EXISTS: 'UserAlreadyExists',
    /**
     * ErrorCodeUserNotFound
     */
    ERROR_CODE_USER_NOT_FOUND: 'UserNotFound'
} as const;

export type ErrorCodeErrorCodeConst = typeof ErrorCodeErrorCodeConst[keyof typeof ErrorCodeErrorCodeConst];

export type GlobalScriptGetGlobalScriptResponseDto = {
    global_script: string;
    updated_at: Date;
};

export type GlobalScriptUpdateGlobalScriptRequestDto = {
    global_script: string;
};

export type GlobalScriptUpdateGlobalScriptResponseDto = {
    [key: string]: unknown;
};

export type SwaggerBaseFailResponse = {
    error_code: ErrorCodeErrorCodeConst;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAny = {
    data: unknown;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthIssueAccessTokenResponseDto = {
    data: AuthIssueAccessTokenResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthLoginResponseDto = {
    data: AuthLoginResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthPasskeyChallengeResponseDto = {
    data: AuthPasskeyChallengeResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthPasskeyGetResponseDto = {
    data: AuthPasskeyGetResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthPasskeyLoginChallengeResponseDto = {
    data: AuthPasskeyLoginChallengeResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthSsoBindingGetResponseDto = {
    data: AuthSsoBindingGetResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthTwoFaGetResponseDto = {
    data: AuthTwoFaGetResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthTwoFaLoginResponseDto = {
    data: AuthTwoFaLoginResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthTwoFaRetrieveTotpResponseDto = {
    data: AuthTwoFaRetrieveTotpResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseAuthTwoFatotpAddResponseDto = {
    data: AuthTwoFatotpAddResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseGlobalScriptGetGlobalScriptResponseDto = {
    data: GlobalScriptGetGlobalScriptResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseGlobalScriptUpdateGlobalScriptResponseDto = {
    data: GlobalScriptUpdateGlobalScriptResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseToolsAllToolsResponseDto = {
    data: ToolsAllToolsResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseToolsCreateToolResponseDto = {
    data: ToolsCreateToolResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseToolsDeleteToolResponseDto = {
    data: ToolsDeleteToolResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseToolsUpdateToolResponseDto = {
    data: ToolsUpdateToolResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseUserCheckUsernameResponseDto = {
    data: UserCheckUsernameResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseUserCreateUserResponseDto = {
    data: UserCreateUserResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseUserDeleteUserResponseDto = {
    data: UserDeleteUserResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseUserUpdateUserResponseDto = {
    data: UserUpdateUserResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type SwaggerBaseSuccessResponseUserUserInfoResponseDto = {
    data: UserUserInfoResponseDto;
    message: string;
    request_id: string;
    status: string;
};

export type ToolsAllToolsResponseDto = {
    tools: Array<ToolsToolDto>;
    tools_last_update_at: Date;
};

export type ToolsCreateToolRequestDto = {
    category: string;
    description: string;
    extra_info: {
        [key: string]: string;
    };
    id: string;
    is_activate: boolean;
    name: string;
    namespace: string;
    realtime_execution: boolean;
    source: string;
    ui_widgets: string;
};

export type ToolsCreateToolResponseDto = {
    [key: string]: unknown;
};

export type ToolsDeleteToolResponseDto = {
    [key: string]: unknown;
};

export type ToolsToolDto = {
    category: string;
    created_at: string;
    description: string;
    extra_info: {
        [key: string]: string;
    };
    is_activate: boolean;
    name: string;
    namespace: string;
    realtime_execution: boolean;
    source: string;
    tool_id: string;
    ui_widgets: string;
    uid: string;
    updated_at: string;
};

export type ToolsUpdateToolRequestDto = {
    category: string;
    description: string;
    extra_info: {
        [key: string]: string;
    };
    id: string;
    is_activate: boolean;
    name: string;
    namespace: string;
    realtime_execution: boolean;
    source: string;
    ui_widgets: string;
};

export type ToolsUpdateToolResponseDto = {
    [key: string]: unknown;
};

export type UserCheckUsernameRequestDto = {
    username: string;
};

export type UserCheckUsernameResponseDto = {
    exists: boolean;
};

export type UserCreateUserRequestDto = {
    password: string;
    username: string;
};

export type UserCreateUserResponseDto = {
    [key: string]: unknown;
};

export type UserDeleteUserResponseDto = {
    [key: string]: unknown;
};

export type UserUpdateUserRequestDto = {
    username?: string;
};

export type UserUpdateUserResponseDto = {
    [key: string]: unknown;
};

export type UserUserInfoResponseDto = {
    id: string;
    mail?: string;
    name: string;
};

export type DeleteApiV1Auth2FaData = {
    /**
     * 2FA type and verification code
     */
    body: AuthTwoFaDeleteRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa';
};

export type DeleteApiV1Auth2FaErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type DeleteApiV1Auth2FaError = DeleteApiV1Auth2FaErrors[keyof DeleteApiV1Auth2FaErrors];

export type DeleteApiV1Auth2FaResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type DeleteApiV1Auth2FaResponse = DeleteApiV1Auth2FaResponses[keyof DeleteApiV1Auth2FaResponses];

export type GetApiV1Auth2FaData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa';
};

export type GetApiV1Auth2FaErrors = {
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type GetApiV1Auth2FaError = GetApiV1Auth2FaErrors[keyof GetApiV1Auth2FaErrors];

export type GetApiV1Auth2FaResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthTwoFaGetResponseDto;
};

export type GetApiV1Auth2FaResponse = GetApiV1Auth2FaResponses[keyof GetApiV1Auth2FaResponses];

export type PostApiV1Auth2FaLoginData = {
    /**
     * 2FA login request
     */
    body: AuthTwoFaLoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/login';
};

export type PostApiV1Auth2FaLoginErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type PostApiV1Auth2FaLoginError = PostApiV1Auth2FaLoginErrors[keyof PostApiV1Auth2FaLoginErrors];

export type PostApiV1Auth2FaLoginResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthTwoFaLoginResponseDto;
};

export type PostApiV1Auth2FaLoginResponse = PostApiV1Auth2FaLoginResponses[keyof PostApiV1Auth2FaLoginResponses];

export type PostApiV1Auth2FaRecoveryData = {
    /**
     * 2FA recovery request
     */
    body: AuthTwoFaRecoveryRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/recovery';
};

export type PostApiV1Auth2FaRecoveryErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type PostApiV1Auth2FaRecoveryError = PostApiV1Auth2FaRecoveryErrors[keyof PostApiV1Auth2FaRecoveryErrors];

export type PostApiV1Auth2FaRecoveryResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type PostApiV1Auth2FaRecoveryResponse = PostApiV1Auth2FaRecoveryResponses[keyof PostApiV1Auth2FaRecoveryResponses];

export type GetApiV1Auth2FaTotpData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/totp';
};

export type GetApiV1Auth2FaTotpErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type GetApiV1Auth2FaTotpError = GetApiV1Auth2FaTotpErrors[keyof GetApiV1Auth2FaTotpErrors];

export type GetApiV1Auth2FaTotpResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthTwoFaRetrieveTotpResponseDto;
};

export type GetApiV1Auth2FaTotpResponse = GetApiV1Auth2FaTotpResponses[keyof GetApiV1Auth2FaTotpResponses];

export type PostApiV1Auth2FaTotpData = {
    /**
     * TOTP verification request
     */
    body: AuthTwoFatotpAddRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/2fa/totp';
};

export type PostApiV1Auth2FaTotpErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
    /**
     * Conflict
     */
    409: SwaggerBaseFailResponse;
};

export type PostApiV1Auth2FaTotpError = PostApiV1Auth2FaTotpErrors[keyof PostApiV1Auth2FaTotpErrors];

export type PostApiV1Auth2FaTotpResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthTwoFatotpAddResponseDto;
};

export type PostApiV1Auth2FaTotpResponse = PostApiV1Auth2FaTotpResponses[keyof PostApiV1Auth2FaTotpResponses];

export type PostApiV1AuthAccessTokenData = {
    /**
     * Refresh token
     */
    body: AuthIssueAccessTokenRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/access-token';
};

export type PostApiV1AuthAccessTokenErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1AuthAccessTokenError = PostApiV1AuthAccessTokenErrors[keyof PostApiV1AuthAccessTokenErrors];

export type PostApiV1AuthAccessTokenResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthIssueAccessTokenResponseDto;
};

export type PostApiV1AuthAccessTokenResponse = PostApiV1AuthAccessTokenResponses[keyof PostApiV1AuthAccessTokenResponses];

export type PostApiV1AuthLoginData = {
    /**
     * Account information
     */
    body: AuthLoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthLoginResponseDto;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type PostApiV1AuthPasskeyLoginChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/login/challenge';
};

export type PostApiV1AuthPasskeyLoginChallengeErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1AuthPasskeyLoginChallengeError = PostApiV1AuthPasskeyLoginChallengeErrors[keyof PostApiV1AuthPasskeyLoginChallengeErrors];

export type PostApiV1AuthPasskeyLoginChallengeResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthPasskeyLoginChallengeResponseDto;
};

export type PostApiV1AuthPasskeyLoginChallengeResponse = PostApiV1AuthPasskeyLoginChallengeResponses[keyof PostApiV1AuthPasskeyLoginChallengeResponses];

export type PostApiV1AuthPasskeyLoginVerifyData = {
    /**
     * Passkey credential assertion response
     */
    body: AuthPasskeyLoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/login/verify';
};

export type PostApiV1AuthPasskeyLoginVerifyErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type PostApiV1AuthPasskeyLoginVerifyError = PostApiV1AuthPasskeyLoginVerifyErrors[keyof PostApiV1AuthPasskeyLoginVerifyErrors];

export type PostApiV1AuthPasskeyLoginVerifyResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthLoginResponseDto;
};

export type PostApiV1AuthPasskeyLoginVerifyResponse = PostApiV1AuthPasskeyLoginVerifyResponses[keyof PostApiV1AuthPasskeyLoginVerifyResponses];

export type PostApiV1AuthPasskeyRegisterChallengeData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/register/challenge';
};

export type PostApiV1AuthPasskeyRegisterChallengeErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type PostApiV1AuthPasskeyRegisterChallengeError = PostApiV1AuthPasskeyRegisterChallengeErrors[keyof PostApiV1AuthPasskeyRegisterChallengeErrors];

export type PostApiV1AuthPasskeyRegisterChallengeResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthPasskeyChallengeResponseDto;
};

export type PostApiV1AuthPasskeyRegisterChallengeResponse = PostApiV1AuthPasskeyRegisterChallengeResponses[keyof PostApiV1AuthPasskeyRegisterChallengeResponses];

export type PostApiV1AuthPasskeyRegisterVerifyData = {
    /**
     * Passkey credential response
     */
    body: AuthPasskeyRegisterRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/register/verify';
};

export type PostApiV1AuthPasskeyRegisterVerifyErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type PostApiV1AuthPasskeyRegisterVerifyError = PostApiV1AuthPasskeyRegisterVerifyErrors[keyof PostApiV1AuthPasskeyRegisterVerifyErrors];

export type PostApiV1AuthPasskeyRegisterVerifyResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type PostApiV1AuthPasskeyRegisterVerifyResponse = PostApiV1AuthPasskeyRegisterVerifyResponses[keyof PostApiV1AuthPasskeyRegisterVerifyResponses];

export type GetApiV1AuthPasskeysData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkeys';
};

export type GetApiV1AuthPasskeysErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type GetApiV1AuthPasskeysError = GetApiV1AuthPasskeysErrors[keyof GetApiV1AuthPasskeysErrors];

export type GetApiV1AuthPasskeysResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthPasskeyGetResponseDto;
};

export type GetApiV1AuthPasskeysResponse = GetApiV1AuthPasskeysResponses[keyof GetApiV1AuthPasskeysResponses];

export type DeleteApiV1AuthPasskeysByPasskeyIdData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path: {
        /**
         * Passkey ID
         */
        passkey_id: bigint;
    };
    query?: never;
    url: '/api/v1/auth/passkeys/{passkey_id}';
};

export type DeleteApiV1AuthPasskeysByPasskeyIdErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
    /**
     * Unauthorized
     */
    401: SwaggerBaseFailResponse;
};

export type DeleteApiV1AuthPasskeysByPasskeyIdError = DeleteApiV1AuthPasskeysByPasskeyIdErrors[keyof DeleteApiV1AuthPasskeysByPasskeyIdErrors];

export type DeleteApiV1AuthPasskeysByPasskeyIdResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type DeleteApiV1AuthPasskeysByPasskeyIdResponse = DeleteApiV1AuthPasskeysByPasskeyIdResponses[keyof DeleteApiV1AuthPasskeysByPasskeyIdResponses];

export type DeleteApiV1AuthSsoBindingsData = {
    /**
     * Delete SSO binding request
     */
    body: AuthSsoBindingDeleteRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/sso/bindings';
};

export type DeleteApiV1AuthSsoBindingsErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type DeleteApiV1AuthSsoBindingsError = DeleteApiV1AuthSsoBindingsErrors[keyof DeleteApiV1AuthSsoBindingsErrors];

export type DeleteApiV1AuthSsoBindingsResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type DeleteApiV1AuthSsoBindingsResponse = DeleteApiV1AuthSsoBindingsResponses[keyof DeleteApiV1AuthSsoBindingsResponses];

export type GetApiV1AuthSsoBindingsData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/sso/bindings';
};

export type GetApiV1AuthSsoBindingsErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type GetApiV1AuthSsoBindingsError = GetApiV1AuthSsoBindingsErrors[keyof GetApiV1AuthSsoBindingsErrors];

export type GetApiV1AuthSsoBindingsResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthSsoBindingGetResponseDto;
};

export type GetApiV1AuthSsoBindingsResponse = GetApiV1AuthSsoBindingsResponses[keyof GetApiV1AuthSsoBindingsResponses];

export type PostApiV1AuthSsoByProviderData = {
    /**
     * OAuth code
     */
    body: AuthSsoLoginRequestDto;
    path: {
        /**
         * SSO provider (github/google)
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/sso/{provider}';
};

export type PostApiV1AuthSsoByProviderErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1AuthSsoByProviderError = PostApiV1AuthSsoByProviderErrors[keyof PostApiV1AuthSsoByProviderErrors];

export type PostApiV1AuthSsoByProviderResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAuthLoginResponseDto;
};

export type PostApiV1AuthSsoByProviderResponse = PostApiV1AuthSsoByProviderResponses[keyof PostApiV1AuthSsoByProviderResponses];

export type PutApiV1AuthSsoByProviderData = {
    /**
     * OAuth code
     */
    body: AuthSsoLoginRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path: {
        /**
         * SSO provider (github/google)
         */
        provider: string;
    };
    query?: never;
    url: '/api/v1/auth/sso/{provider}';
};

export type PutApiV1AuthSsoByProviderErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PutApiV1AuthSsoByProviderError = PutApiV1AuthSsoByProviderErrors[keyof PutApiV1AuthSsoByProviderErrors];

export type PutApiV1AuthSsoByProviderResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type PutApiV1AuthSsoByProviderResponse = PutApiV1AuthSsoByProviderResponses[keyof PutApiV1AuthSsoByProviderResponses];

export type GetApiV1GlobalScriptData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/global-script';
};

export type GetApiV1GlobalScriptErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type GetApiV1GlobalScriptError = GetApiV1GlobalScriptErrors[keyof GetApiV1GlobalScriptErrors];

export type GetApiV1GlobalScriptResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseGlobalScriptGetGlobalScriptResponseDto;
};

export type GetApiV1GlobalScriptResponse = GetApiV1GlobalScriptResponses[keyof GetApiV1GlobalScriptResponses];

export type PutApiV1GlobalScriptData = {
    /**
     * Global script body
     */
    body: GlobalScriptUpdateGlobalScriptRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/global-script';
};

export type PutApiV1GlobalScriptErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PutApiV1GlobalScriptError = PutApiV1GlobalScriptErrors[keyof PutApiV1GlobalScriptErrors];

export type PutApiV1GlobalScriptResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseGlobalScriptUpdateGlobalScriptResponseDto;
};

export type PutApiV1GlobalScriptResponse = PutApiV1GlobalScriptResponses[keyof PutApiV1GlobalScriptResponses];

export type GetApiV1HealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/healthcheck';
};

export type GetApiV1HealthcheckErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type GetApiV1HealthcheckError = GetApiV1HealthcheckErrors[keyof GetApiV1HealthcheckErrors];

export type GetApiV1HealthcheckResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseAny;
};

export type GetApiV1HealthcheckResponse = GetApiV1HealthcheckResponses[keyof GetApiV1HealthcheckResponses];

export type GetApiV1ToolsData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tools';
};

export type GetApiV1ToolsErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type GetApiV1ToolsError = GetApiV1ToolsErrors[keyof GetApiV1ToolsErrors];

export type GetApiV1ToolsResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseToolsAllToolsResponseDto;
};

export type GetApiV1ToolsResponse = GetApiV1ToolsResponses[keyof GetApiV1ToolsResponses];

export type PostApiV1ToolsCreateData = {
    /**
     * Tool definition
     */
    body: ToolsCreateToolRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tools/create';
};

export type PostApiV1ToolsCreateErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1ToolsCreateError = PostApiV1ToolsCreateErrors[keyof PostApiV1ToolsCreateErrors];

export type PostApiV1ToolsCreateResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseToolsCreateToolResponseDto;
};

export type PostApiV1ToolsCreateResponse = PostApiV1ToolsCreateResponses[keyof PostApiV1ToolsCreateResponses];

export type DeleteApiV1ToolsByToolUidData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path: {
        /**
         * Tool unique identifier (UID)
         */
        tool_uid: string;
    };
    query?: never;
    url: '/api/v1/tools/{tool_uid}';
};

export type DeleteApiV1ToolsByToolUidErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type DeleteApiV1ToolsByToolUidError = DeleteApiV1ToolsByToolUidErrors[keyof DeleteApiV1ToolsByToolUidErrors];

export type DeleteApiV1ToolsByToolUidResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseToolsDeleteToolResponseDto;
};

export type DeleteApiV1ToolsByToolUidResponse = DeleteApiV1ToolsByToolUidResponses[keyof DeleteApiV1ToolsByToolUidResponses];

export type PutApiV1ToolsByToolUidData = {
    /**
     * Fields to update
     */
    body: ToolsUpdateToolRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path: {
        /**
         * Tool identifier
         */
        tool_uid: string;
    };
    query?: never;
    url: '/api/v1/tools/{tool_uid}';
};

export type PutApiV1ToolsByToolUidErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PutApiV1ToolsByToolUidError = PutApiV1ToolsByToolUidErrors[keyof PutApiV1ToolsByToolUidErrors];

export type PutApiV1ToolsByToolUidResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseToolsUpdateToolResponseDto;
};

export type PutApiV1ToolsByToolUidResponse = PutApiV1ToolsByToolUidResponses[keyof PutApiV1ToolsByToolUidResponses];

export type GetApiV1UserData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type GetApiV1UserErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type GetApiV1UserError = GetApiV1UserErrors[keyof GetApiV1UserErrors];

export type GetApiV1UserResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseUserUserInfoResponseDto;
};

export type GetApiV1UserResponse = GetApiV1UserResponses[keyof GetApiV1UserResponses];

export type PostApiV1UserCheckData = {
    /**
     * Username to check
     */
    body: UserCheckUsernameRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/user/check';
};

export type PostApiV1UserCheckErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1UserCheckError = PostApiV1UserCheckErrors[keyof PostApiV1UserCheckErrors];

export type PostApiV1UserCheckResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseUserCheckUsernameResponseDto;
};

export type PostApiV1UserCheckResponse = PostApiV1UserCheckResponses[keyof PostApiV1UserCheckResponses];

export type PostApiV1UserCreateData = {
    /**
     * New user information
     */
    body: UserCreateUserRequestDto;
    path?: never;
    query?: never;
    url: '/api/v1/user/create';
};

export type PostApiV1UserCreateErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PostApiV1UserCreateError = PostApiV1UserCreateErrors[keyof PostApiV1UserCreateErrors];

export type PostApiV1UserCreateResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseUserCreateUserResponseDto;
};

export type PostApiV1UserCreateResponse = PostApiV1UserCreateResponses[keyof PostApiV1UserCreateResponses];

export type DeleteApiV1UserDeleteData = {
    body?: never;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/user/delete';
};

export type DeleteApiV1UserDeleteErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type DeleteApiV1UserDeleteError = DeleteApiV1UserDeleteErrors[keyof DeleteApiV1UserDeleteErrors];

export type DeleteApiV1UserDeleteResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseUserDeleteUserResponseDto;
};

export type DeleteApiV1UserDeleteResponse = DeleteApiV1UserDeleteResponses[keyof DeleteApiV1UserDeleteResponses];

export type PutApiV1UserInfoData = {
    /**
     * Fields to update (only non-null fields will be updated)
     */
    body: UserUpdateUserRequestDto;
    headers: {
        /**
         * Bearer access token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/user/info';
};

export type PutApiV1UserInfoErrors = {
    /**
     * Bad Request
     */
    400: SwaggerBaseFailResponse;
};

export type PutApiV1UserInfoError = PutApiV1UserInfoErrors[keyof PutApiV1UserInfoErrors];

export type PutApiV1UserInfoResponses = {
    /**
     * OK
     */
    200: SwaggerBaseSuccessResponseUserUpdateUserResponseDto;
};

export type PutApiV1UserInfoResponse = PutApiV1UserInfoResponses[keyof PutApiV1UserInfoResponses];
