package main

// WARNING: this generator must only be invoked via go:generate from
// internal/error_code; running it elsewhere will write files to the wrong place.

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	errorcode "ya-tool-craft/internal/error_code"
)

func main() {
	if err := generateConstants(); err != nil {
		panic(err)
	}
}

func generateConstants() error {
	codes := make([]errorcode.ErrorCode, len(errorcode.ErrorCodeList))
	copy(codes, errorcode.ErrorCodeList)
	sort.SliceStable(codes, func(i, j int) bool {
		return codes[i].Code < codes[j].Code
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	buf.WriteString("package error_code\n\n")
	buf.WriteString("type ErrorCodeConst string\n\n")
	buf.WriteString("const (\n")
	for _, c := range codes {
		fmt.Fprintf(&buf, "\tErrorCode%s ErrorCodeConst = %q\n", c.Code, c.Code)
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	outputPath := filepath.Join(".", "error_code_consts_gen.go")
	return os.WriteFile(outputPath, formatted, 0o644)
}
